# Generated by Django 4.0 on 2024-03-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_fileupload_delete_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ('-created_datetime',)},
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
